import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Libreria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex items-center justify-center w-full gap-5 mt-5">
          <Link href="/" className="link">
            Inicio
          </Link>
          <Link href="/dashboard/actualizar" className="link">
            Dashboard
          </Link>
          <Link href="/about" className="link">
            About
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
